# Generated by tools/homebrew-formula.sh in renerocksai/omajot for v0.1.6. Do not edit:
# the next release replaces this file.
class Omajot < Formula
  desc "Markdown notes that sync through your own hub over Tailscale"
  homepage "https://renerocks.ai/omajot/"
  version "0.1.6"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/renerocksai/omajot/releases/download/v0.1.6/omajot-aarch64-macos"
      sha256 "a521be5622f753a9a5c2c0917acd4cad73764bf3f378b0570cebd476749f8940"
    end
    on_intel do
      url "https://github.com/renerocksai/omajot/releases/download/v0.1.6/omajot-x86_64-macos"
      sha256 "895f57dcce4a3cf2017dfcf74c1c7f7f83f501f3773372f7ac0e39ea78310a70"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/renerocksai/omajot/releases/download/v0.1.6/omajot-aarch64-linux"
      sha256 "f9a33370dc629a8385d0c4c98a465d2af3b710979ac747cd3d2f257d20e5a74d"
    end
    on_intel do
      url "https://github.com/renerocksai/omajot/releases/download/v0.1.6/omajot-x86_64-linux"
      sha256 "96bfeafbf7cbbae34f04fe9bedb14f48b766ca61b94b388c30a8efa377daf30e"
    end
  end

  def install
    bin.install Dir["omajot-*"].first => "omajot"
  end

  # brew services start omajot: the hub, started at login and restarted if it
  # stops. It reads hub_login (and hub_port, hub_data) from
  # ~/.config/omajot/config.json.
  service do
    run [opt_bin/"omajot", "hub"]
    keep_alive true
    log_path var/"log/omajot-hub.log"
    error_log_path var/"log/omajot-hub.log"
  end

  def caveats
    <<~TEXT
      To run the hub on this computer, write your Tailscale login to
      ~/.config/omajot/config.json once:

        {"hub_login": "you@example.com"}

      Then start the hub and publish it on your tailnet:

        brew services start omajot
        tailscale serve --bg --https=8443 http://127.0.0.1:8787

      The notes are in ~/omajot-data. The log is in
      #{var}/log/omajot-hub.log. Guide: https://renerocks.ai/omajot/get-started.html
    TEXT
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/omajot --version")
  end
end
