# Generated by tools/homebrew-formula.sh in renerocksai/omajot for v0.1.2. Do not edit:
# the next release replaces this file.
class Omajot < Formula
  desc "Markdown notes that sync through your own hub over Tailscale"
  homepage "https://renerocks.ai/omajot/"
  version "0.1.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/renerocksai/omajot/releases/download/v0.1.2/omajot-aarch64-macos"
      sha256 "22773c205f13d9ce0554a30d676a969fe1690ef7477ae205f3eb1cce9fba659f"
    end
    on_intel do
      url "https://github.com/renerocksai/omajot/releases/download/v0.1.2/omajot-x86_64-macos"
      sha256 "d800f7c388a26adbc17671c410ea54730e51378f79056b29e87bc910c459dcaa"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/renerocksai/omajot/releases/download/v0.1.2/omajot-aarch64-linux"
      sha256 "e2ac4cd14d1962236df74ea031ccf3a40f807eb161a78ee4089a54d6d8d11c29"
    end
    on_intel do
      url "https://github.com/renerocksai/omajot/releases/download/v0.1.2/omajot-x86_64-linux"
      sha256 "3d3057037dc910ea2a437208d9d09d9938a4400b08001cec43bd038c9e2d78bb"
    end
  end

  def install
    bin.install Dir["omajot-*"].first => "omajot"
  end

  # brew services start omajot: the hub, started at login and restarted if it
  # stops. It reads hub_login (and hub_port, hub_data) from
  # ~/.config/omajot/config.json.
  service do
    run [opt_bin/"omajot", "hub"]
    keep_alive true
    log_path var/"log/omajot-hub.log"
    error_log_path var/"log/omajot-hub.log"
  end

  def caveats
    <<~TEXT
      To run the hub on this computer, write your Tailscale login to
      ~/.config/omajot/config.json once:

        {"hub_login": "you@example.com"}

      Then start the hub and publish it on your tailnet:

        brew services start omajot
        tailscale serve --bg --https=8443 http://127.0.0.1:8787

      The notes are in ~/omajot-data. The log is in
      #{var}/log/omajot-hub.log. Guide: https://renerocks.ai/omajot/get-started.html
    TEXT
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/omajot --version")
  end
end
