# Generated by tools/homebrew-formula.sh in renerocksai/omajot for v0.1.11. Do not edit:
# the next release replaces this file.
class Omajot < Formula
  desc "Markdown notes that sync through your own hub over Tailscale"
  homepage "https://renerocks.ai/omajot/"
  version "0.1.11"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/renerocksai/omajot/releases/download/v0.1.11/omajot-aarch64-macos"
      sha256 "cb71f8b81a2bbe644b1c8c7c1ab81429baf088f29b392223f599a94460b09d15"
    end
    on_intel do
      url "https://github.com/renerocksai/omajot/releases/download/v0.1.11/omajot-x86_64-macos"
      sha256 "75f804fe15e58c02292fde7b9ad14328dbf3aac545e0c2b7240b26ebae21c3eb"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/renerocksai/omajot/releases/download/v0.1.11/omajot-aarch64-linux"
      sha256 "66658cf5468256197ff12ef5e5a2e5a85b318af7295a7bc5848133273e7e0021"
    end
    on_intel do
      url "https://github.com/renerocksai/omajot/releases/download/v0.1.11/omajot-x86_64-linux"
      sha256 "a8fd48ba7fc079b2e8e264b9c840976fe7dc14fef974d468aee8e34bb9cbd4f6"
    end
  end

  def install
    bin.install Dir["omajot-*"].first => "omajot"
  end

  # brew services start omajot: the hub, started at login and restarted if it
  # stops. It reads hub_login (and hub_port, hub_data) from
  # ~/.config/omajot/config.json.
  service do
    run [opt_bin/"omajot", "hub"]
    keep_alive true
    log_path var/"log/omajot-hub.log"
    error_log_path var/"log/omajot-hub.log"
  end

  def caveats
    <<~TEXT
      To run the hub on this computer, write your Tailscale login to
      ~/.config/omajot/config.json once:

        {"hub_login": "you@example.com"}

      Then start the hub and publish it on your tailnet:

        brew services start omajot
        tailscale serve --bg --https=8443 http://127.0.0.1:8787

      The notes are in ~/omajot-data. The log is in
      #{var}/log/omajot-hub.log. Guide: https://renerocks.ai/omajot/get-started.html
    TEXT
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/omajot --version")
  end
end
